### ISSUE TITLE
dropbox.com

### ISSUE THREAD

**Issue by injust** [ryanbr/fanboy-adblock#1120] opened 2019-08-05 06:46 UTC
### List the website(s) you're having issues:
`dropbox.com`

### What happens?
`Download` and `Share` buttons are removed in file previews

### List Subscriptions you're using:
Fanboy's Annoyance List

### Other details:
Rule `/share_button.` is blocking `https://cfl.dropboxstatic.com/static/compiled/js/modules/clean/react/file_viewer/share_button.min-vfl8yhDaX.js`

**Comment by krystian3w** [comment] 2019-08-07 17:15
duplicate of #959

**Comment by krystian3w** [comment] 2019-08-07 17:17
Duplicate of #959

**Comment by ryanbr** [comment] 2019-08-10 11:26
https://github.com/easylist/easylist/commit/5657993edef055083e8014bf6936d1165c764ff3

**Closed by ryanbr** 2019-08-10 11:26 UTC
