### ISSUE TITLE
Yahoo / Oath bad filters in Cookie list

### ISSUE THREAD

**Issue by krystian3w** [ryanbr/fanboy-adblock#1003] opened 2019-04-10 15:50 UTC
## URL [](https://github.com/MajkiIT/polish-ads-filter/issues/12824)

```
https://consent.yahoo.com/collectConsent?sessionId=3_cc-session_3fc41adb-f16a-4965-8bc9-a2d90e319ddc&lang=&inline=false
```

## Exception

```
yahoo.com#@#.consent-container
```

## Screenshots

Before:

![obraz](https://i.imgur.com/i1ILW5T.png) |
--- |

After:

![obraz](https://i.imgur.com/4Dbd6aG.png) |
--- |

**Comment by kulfoon** [comment] 2019-04-10 16:05
Duplicate of https://github.com/ryanbr/fanboy-adblock/issues/980.

**Closed** 2019-04-11 15:18 UTC
