### ISSUE TITLE
theverge.com

### ISSUE THREAD

**Issue by KonoromiHimaries** [ryanbr/fanboy-adblock#657] opened 2018-11-13 06:47 UTC
### Describe the issue

cookie

### Screenshot(s)

![2018-11-13-the verge](https://user-images.githubusercontent.com/5884000/48395660-4523b700-e718-11e8-8047-a100f6821bff.png)

### Versions
Browser/version: [here] chrome latest release
uBlock Origin version: [here] latest release

### Settings
https://gist.github.com/KonoromiHimaries/ce463027dda8ce57b01bb5639009f21e

**Comment by bogachenko** [comment] 2018-11-13 08:34
@ryanbr which video? I have nothing like that.

@KonoromiHimaries 
`theverge.com###privacy-consent`

**Comment by kulfoon** [comment] 2018-11-13 12:20
"I don't care about cookies" already remove this by the same filter and the example videos still works (also checked on 2 browsers Firefox and Opera):
`https://www.theverge.com/2018/11/12/18089002/stan-lee-cameos-marvel-movies-death-avengers-infinity-war-spider-man-iron-man`

Anyway I've found another issue https://github.com/easylist/easylist/issues/2285

**Comment by krystian3w** [comment] 2018-11-13 13:04
`##body:not(:has(.c-video-embed)) #privacy-consent`

 but this is no works because has no arrive to CSS in browser specifications.

An similar filter:
 `#?#body:not(:-abp-has(.c-video-embed)) #privacy-consent`

 is invalid or still cut to much.

https://css4-selectors.com/selector/css4/relational-pseudo-class/

**Comment by THEtomaso** [comment] 2018-11-13 19:20
> "I don't care about cookies" already remove this by the same filter and the example videos still works fine

Only the first one.
The second video doesn't even show at my end, if the cookie consent is blocked.

I reported this issue to the author of '**I don't care about cookies**' on the same day as I filed the '**EasyList**' report.
The author has already confirmed the issue, and promises a fix in the next version.

**Comment by krystian3w** [comment] 2018-11-13 19:24
I confirm embeded youtube wideo with `voxmedia.com` won't play with accept cookie in pop-up / bar message.

**Comment by ryanbr** [comment] 2018-11-17 02:46
Closing, Will need snippet support, which maybe fix this?

**Closed by ryanbr** 2018-11-17 02:46 UTC
